#!/usr/bin/env ansible-playbook
#Python Packages - installed from pypi using pip
---
- name: "Install python packages"
  pip: name={{item}} state=present
    with_items:
      - ipdb
      - docker
      - docker-composer
      #Vim
      - grip
      - html-tree-diff
      - pandocfilters
