#!/usr/bin/env ansible-playbook
---
- name: "Install i3 packages"
  apt: name={{item}} state=installed
  with_items:
  - i3
  - dunst
  - i3lock
  - i3status
  - suckless-tools
  become: yes

- name: "Install i3-gaps dependencies"
  apt: name={{item}} state=installed
  with_items:
  - libxcb1-dev
  - libxcb-keysyms1-dev
  - libpango1.0-dev
  - libxcb-util0-dev
  - libxcb-icccm4-dev
  - libyajl-dev
  - libstartup-notification0-dev
  - libxcb-randr0-dev
  - libev-dev
  - libxcb-cursor-dev
  - libxcb-xinerama0-dev
  - libxcb-xkb-dev
  - libxkbcommon-dev
  - libxkbcommon-x11-dev
