#!/usr/bin/env ansible-playbook
# Apps - Things installed with apt-get
---
- name: "Install signing keys for standalone packages"
  apt_key: id={{item}} keyserver=keyserver.ubuntu.com state=present
  with_items:
    - E1DF1F24 # Git Core
    - 009ED615 # Shutter
    - 8231B6DD # NeoVim
    - 4716DAB5 # Mixxx
    - BBEBDCB318AD50EC6865090613B00F1FD2C19886 # SPOTIFY
    - 852541CB # Audacity

- name: "Add Repos for standalone packages"
  apt_repository: repo="{{item}}" state=present update_cache=yes
  ignore_errors: True
  with_items:
    - "deb http://ppa.launchpad.net/git-core/ppa/ubuntu {{ ansible_distribution_release }} main "
    - "deb http://ppa.launchpad.net/shutter/ppa/ubuntu {{ ansible_distribution_release }} main"
    - "deb http://ppa.launchpad.net/neovim-ppa/unstable/ubuntu {{ ansible_distribution_release }} main "
    - "deb http://ppa.launchpad.net/mixxx/mixxx/ubuntu {{ ansible_distribution_release }} main"
    - "deb http://repository.spotify.com stable non-free"
    - "deb http://ppa.launchpad.net/ubuntuhandbook1/audacity/ubuntu {{ ansible_distribution_release }} main "

- name: "Install standalone packages" 
  apt: name={{item}} state=installed
  ignore_errors: True
  with_items:
    #Desktop Apps
    - touchegg
    - shutter
    - xdotool
    - mixxx
    - spotify-client
    #Languages
    - nodejs
    - golang
    - openjdk-7-jdk
    - cabal-install
    #Dev Tools
    - git
    - neovim
    - vim-gtk
    - automake
    - gcc
    - cmake
    - gdb
    - valgrind
    - exuberant-ctags
    - pylint
    - llvm-3.6
    - markdown
    - texlive-full
    - texlive-latex-extra
    #GUI Utils
    - audacity
    - gnucash
    #Security Tools
    - apparmor
    #Shells
    - fish
    - zsh
    #CLI Utilities
    - toilet
    - nmap
    - ranger
