#!/usr/bin/env ansible-playbook
---
- name: "Install vim Plugin Dependencies"
  apt: name={{item}} state=installed
  with_items:
    - astyle
    - ack-grep
    - silversearcher-ag
    - python-autopep8
    - tidy
    - pylint
    - exuberant-ctags
    - cscope
  become: yes
